# DON'T use this file directly.
#
# It is used to extend sample.oid.toml for development purposes.

[types]
containers = [
    "PWD/types/array_type.toml",
    "PWD/types/string_type.toml",
    "PWD/types/cxx11_string_type.toml",
    "PWD/types/folly_iobuf_type.toml",
    "PWD/types/folly_iobuf_queue_type.toml",
    "PWD/types/set_type.toml",
    "PWD/types/unordered_set_type.toml",
    "PWD/types/seq_type.toml",
    "PWD/types/list_type.toml",
    "PWD/types/cxx11_list_type.toml",
    "PWD/types/deque_list_type.toml",
    "PWD/types/shrd_ptr_type.toml",
    "PWD/types/uniq_ptr_type.toml",
    "PWD/types/std_map_type.toml",
    "PWD/types/std_unordered_map_type.toml",
    "PWD/types/pair_type.toml",
    "PWD/types/stack_container_adapter_type.toml",
    "PWD/types/queue_container_adapter_type.toml",
    "PWD/types/priority_queue_container_adapter_type.toml",
    "PWD/types/ref_wrapper_type.toml",
    "PWD/types/multi_map_type.toml",
    "PWD/types/folly_small_heap_vector_map.toml",
    "PWD/types/folly_optional_type.toml",
    "PWD/types/optional_type.toml",
    "PWD/types/try_type.toml",
    "PWD/types/fb_string_type.toml",
    "PWD/types/small_vec_type.toml",
    "PWD/types/f14_fast_map.toml",
    "PWD/types/f14_node_map.toml",
    "PWD/types/f14_vector_map.toml",
    "PWD/types/f14_fast_set.toml",
    "PWD/types/f14_node_set.toml",
    "PWD/types/f14_vector_set.toml",
    "PWD/types/sorted_vec_set_type.toml",
    "PWD/types/map_seq_type.toml",
    "PWD/types/boost_bimap_type.toml",
    "PWD/types/repeated_field_type.toml",
    "PWD/types/repeated_ptr_field_type.toml",
    "PWD/types/caffe2_blob_type.toml",
    "PWD/types/std_variant.toml",
    "PWD/types/thrift_isset_type.toml",
]
