[info]
type_name = "apache::thrift::detail::isset_bitset"
ctype = "THRIFT_ISSET_TYPE"
header = "thrift/lib/cpp2/gen/module_types_h.h"
required_features = ["capture-thrift-isset"]

# Old:
typeName = "apache::thrift::detail::isset_bitset<"
ns = ["apache::thrift::detail::isset_bitset"]
numTemplateParams = 2
replaceTemplateParamIndex = []

[codegen]
decl = """
// DummyDecl %1%
"""
func = """
// DummyFunc %1%
"""

traversal_func = """
return returnArg;
"""
